AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyTestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Access to the host
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

Outputs:
  SecurityGroup:
    Description: Name of the security group
    Value: !Ref MyTestSecurityGroup
    Export:
      Name: !Sub SecurityGroup-${AWS::StackName}
